name: dailymotion_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #--------------Firebase--------------
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  
  #--------------Bloc Cubit--------------#
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  #--------------GetIt--------------#
  get_it: ^7.2.0
  #--------------Dio--------------#
  dio: ^5.2.0
  dartz: ^0.10.1
  #--------------Responsive UI--------------#
  kartal:
  #--------------Lottie--------------#
  lottie: ^2.3.0
  #--------------Webview--------------#
  webview_flutter:
  #----------------Hive---------------#
  hive: ^2.2.3
  hive_flutter: ^1.1.0
 #-------------File Picker------------#
  file_picker: ^6.1.1
  permission_handler: ^11.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner:
  hive_generator: ^2.0.1



flutter:
  uses-material-design: true
  
  assets:
  - assets/images/
  - assets/lotties/
